# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import django.contrib.auth.models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPartMaster',
            fields=[
                ('body_part_id', models.AutoField(serialize=False, primary_key=True)),
                ('body_part_name', models.CharField(max_length=50)),
                ('body_part_created_by', models.CharField(max_length=50, null=True)),
                ('body_part_updated_by', models.CharField(max_length=50, null=True)),
                ('body_part_created_date', models.DateTimeField(null=True)),
                ('body_part_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 258548))),
                ('body_part_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='CustomerImage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('customer_image', models.ImageField(default=None, upload_to=b'', max_length=255, verbose_name=b'Image')),
            ],
        ),
        migrations.CreateModel(
            name='ExcerciseVideo',
            fields=[
                ('exercise_video_id', models.AutoField(serialize=False, primary_key=True)),
                ('exercise_video_name', models.CharField(max_length=50)),
                ('exercise_video_url', models.FileField(max_length=50, upload_to=b'')),
                ('exercise_video_created_by', models.CharField(max_length=50, null=True)),
                ('exercise_video_updated_by', models.CharField(max_length=50, null=True)),
                ('exercise_video_created_date', models.DateTimeField(null=True)),
                ('exercise_video_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 259237))),
                ('exercise_video_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(serialize=False, primary_key=True)),
                ('exercise_name', models.CharField(max_length=50)),
                ('exercise_gender', models.CharField(max_length=50, choices=[(b'male', b'male'), (b'female', b'female')])),
                ('exercise_gym_access', models.CharField(default=True, max_length=50, null=True, choices=[(b'yes', b'yes'), (b'no', b'no')])),
                ('exercise_time', models.CharField(max_length=50, null=True)),
                ('exercise_intensity', models.CharField(max_length=50, null=True)),
                ('exercise_created_by', models.CharField(max_length=50, null=True)),
                ('exercise_updated_by', models.CharField(max_length=50, null=True)),
                ('exercise_created_date', models.DateTimeField(null=True)),
                ('exercise_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 259997))),
                ('exercise_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('exercise_body_part_id', models.ForeignKey(related_name='exercise_body_part', to='trainmefitapp.BodyPartMaster', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionMaster',
            fields=[
                ('instruction_id', models.AutoField(serialize=False, primary_key=True)),
                ('instruction_name', models.CharField(max_length=50)),
                ('instruction_created_by', models.CharField(max_length=50, null=True)),
                ('instruction_updated_by', models.CharField(max_length=50, null=True)),
                ('instruction_created_date', models.DateTimeField(null=True)),
                ('instruction_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 260817))),
                ('instruction_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('instruction_exercise_id', models.ForeignKey(related_name='exercise_instruction', to='trainmefitapp.Exercise', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipMaster',
            fields=[
                ('membership_id', models.AutoField(serialize=False, primary_key=True)),
                ('membership_type', models.CharField(max_length=70)),
                ('membership_duration', models.CharField(max_length=50)),
                ('membership_description', models.CharField(max_length=70)),
                ('membership_created_by', models.CharField(max_length=50, null=True)),
                ('membership_updated_by', models.CharField(max_length=50, null=True)),
                ('membership_created_date', models.DateTimeField(null=True)),
                ('membership_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 255718))),
                ('membership_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveMaster',
            fields=[
                ('objective_id', models.AutoField(serialize=False, primary_key=True)),
                ('objective_name', models.CharField(max_length=50, null=True)),
                ('objective_created_by', models.CharField(max_length=50, null=True)),
                ('objective_updated_by', models.CharField(max_length=50, null=True)),
                ('objective_created_date', models.DateTimeField(null=True)),
                ('objective_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 256379))),
                ('objective_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='ProgramMaster',
            fields=[
                ('program_id', models.AutoField(serialize=False, primary_key=True)),
                ('program_name', models.CharField(max_length=50, null=True)),
                ('program_user_gender', models.CharField(default=True, max_length=50, choices=[(b'male', b'male'), (b'female', b'female')])),
                ('program_gym_access', models.CharField(default=True, max_length=50, blank=True, choices=[(b'yes', b'yes'), (b'no', b'no')])),
                ('program_total_days', models.IntegerField(null=True)),
                ('program_created_by', models.CharField(max_length=50, null=True)),
                ('program_updated_by', models.CharField(max_length=50, null=True)),
                ('program_created_date', models.DateTimeField(null=True)),
                ('program_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 262307))),
                ('program_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('program_user_objective_id', models.ForeignKey(related_name='user_program_objective', to='trainmefitapp.ObjectiveMaster', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramWorkoutMap',
            fields=[
                ('program_workout_id', models.AutoField(serialize=False, primary_key=True)),
                ('program_workout_day', models.CharField(max_length=50, null=True)),
                ('workout_program_created_by', models.CharField(max_length=50, null=True)),
                ('workout_program_updated_by', models.CharField(max_length=50, null=True)),
                ('workout_program_created_date', models.DateTimeField(null=True)),
                ('workout_program_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 263888))),
                ('workout_program_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('program_id', models.ForeignKey(related_name='workout_program_id', to='trainmefitapp.ProgramMaster', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleWorkout',
            fields=[
                ('sample_workout_id', models.AutoField(serialize=False, primary_key=True)),
                ('sample_workout_name', models.CharField(max_length=50, null=True)),
                ('sample_workout_description', models.CharField(max_length=50, null=True)),
                ('sample_workout_created_by', models.CharField(max_length=50, null=True)),
                ('sample_workout_updated_by', models.CharField(max_length=50, null=True)),
                ('sample_workout_created_date', models.DateTimeField(null=True)),
                ('sample_workout_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 267816))),
                ('sample_workout_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.CharField(max_length=50, unique=True, null=True)),
                ('user_first_name', models.CharField(max_length=50, null=True, blank=True)),
                ('user_last_name', models.CharField(max_length=40, null=True, blank=True)),
                ('user_phone_number', models.CharField(max_length=50, null=True, blank=True)),
                ('user_gender', models.CharField(default=True, max_length=50, blank=True, choices=[(b'male', b'male'), (b'female', b'female')])),
                ('user_dob', models.DateField(null=True, verbose_name=b'Date Of Birth', blank=True)),
                ('user_city', models.CharField(max_length=50, null=True, blank=True)),
                ('user_state', models.CharField(max_length=50, null=True, blank=True)),
                ('user_country', models.CharField(max_length=50, null=True, blank=True)),
                ('user_sign_up_source', models.CharField(max_length=10, blank=True)),
                ('user_height', models.FloatField(null=True, blank=True)),
                ('user_weight', models.FloatField(null=True, blank=True)),
                ('user_gym_access', models.CharField(default=True, max_length=50, blank=True, choices=[(b'yes', b'yes'), (b'no', b'no')])),
                ('user_workouts_per_week', models.PositiveIntegerField(default=3, blank=True)),
                ('user_leg_press_weight_lift', models.FloatField(null=True, blank=True)),
                ('user_bench_press_weight_lift', models.FloatField(null=True, blank=True)),
                ('user_bicep_curls_weight_lift', models.FloatField(null=True, blank=True)),
                ('user_workout_intensity', models.CharField(default=False, max_length=50, blank=True, choices=[(b'easy', b'easy'), (b'medium', b'medium'), (b'hard', b'hard')])),
                ('user_membership_status', models.CharField(max_length=10, null=True, blank=True)),
                ('user_profile_picture', models.ImageField(default=None, upload_to=b'customer_images/', max_length=255, verbose_name=b'Image')),
                ('user_created_by', models.CharField(max_length=50, null=True)),
                ('user_updated_by', models.CharField(max_length=50, null=True)),
                ('user_created_date', models.DateTimeField(null=True)),
                ('user_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 257281))),
                ('user_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('user_membership_id', models.ForeignKey(related_name='user_membership', to='trainmefitapp.MembershipMaster', null=True)),
                ('user_objective_id', models.ForeignKey(related_name='user_objective', to='trainmefitapp.ObjectiveMaster', null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProgramExerciseMap',
            fields=[
                ('user_program_exercise_id', models.AutoField(serialize=False, primary_key=True)),
                ('exercise_id', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_name', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_time', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_workout_total_sets', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_workout_total_reps', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_workout_time_between_set', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_workout_total_time', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_workout_rest_time', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_created_by', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_updated_by', models.CharField(max_length=50, null=True)),
                ('user_program_exercise_created_date', models.DateTimeField(null=True)),
                ('user_program_exercise_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 266564))),
                ('user_program_exercise_workout_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('user_program_exercise_body_part_id', models.ForeignKey(related_name='user_exercise_body_part', to='trainmefitapp.BodyPartMaster', null=True)),
                ('user_program_exercise_video_id', models.ForeignKey(related_name='user_exercise_video', to='trainmefitapp.ExcerciseVideo', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgramMap',
            fields=[
                ('user_program_id', models.AutoField(serialize=False, primary_key=True)),
                ('user_program_name', models.CharField(max_length=50, null=True)),
                ('user_program_start_date', models.DateField(null=True)),
                ('user_program_end_date', models.DateField(null=True)),
                ('user_program_created_by', models.CharField(max_length=50, null=True)),
                ('user_program_updated_by', models.CharField(max_length=50, null=True)),
                ('user_program_created_date', models.DateTimeField(null=True)),
                ('user_program_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 264639))),
                ('user_program_program_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('program_id', models.ForeignKey(related_name='program_user_id', to='trainmefitapp.ProgramMaster', null=True)),
                ('user_id', models.ForeignKey(related_name='user_program_id', to='trainmefitapp.UserProfile', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgramWorkoutMaster',
            fields=[
                ('user_program_workout_id', models.AutoField(serialize=False, primary_key=True)),
                ('user_program_workout_name', models.CharField(max_length=50, null=True)),
                ('user_program_workout_total_execise', models.CharField(max_length=50, null=True)),
                ('user_program_workout_total_time', models.CharField(max_length=50, null=True)),
                ('user_program_workout_type', models.CharField(max_length=50, null=True)),
                ('user_program_workout_day', models.CharField(max_length=50, null=True)),
                ('user_program_workout_intensity', models.CharField(max_length=50, null=True)),
                ('user_program_workout_created_by', models.CharField(max_length=50, null=True)),
                ('user_program_workout_updated_by', models.CharField(max_length=50, null=True)),
                ('user_program_workout_created_date', models.DateTimeField(null=True)),
                ('user_program_workout_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 265601))),
                ('user_program_workout_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('user_program_id', models.ForeignKey(related_name='program_user_workout_id', to='trainmefitapp.UserProgramMap', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(serialize=False, primary_key=True)),
                ('workout_name', models.CharField(max_length=50, null=True)),
                ('workout_total_no_execise', models.IntegerField(null=True)),
                ('workout_total_time', models.CharField(max_length=50, null=True)),
                ('workout_intensity', models.CharField(max_length=50, null=True)),
                ('workout_type', models.CharField(max_length=50, null=True)),
                ('workout_created_by', models.CharField(max_length=50, null=True)),
                ('workout_updated_by', models.CharField(max_length=50, null=True)),
                ('workout_created_date', models.DateTimeField(null=True)),
                ('workout_updated_date', models.DateTimeField(default=datetime.datetime(2015, 8, 25, 11, 33, 19, 261491))),
                ('workout_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExerciseMap',
            fields=[
                ('workout_exercise_id', models.AutoField(serialize=False, primary_key=True)),
                ('workout_exercise_total_sets', models.CharField(max_length=50, null=True)),
                ('workout_exercise_total_reps', models.CharField(max_length=50, null=True)),
                ('workout_exercise_total_time', models.CharField(max_length=50, null=True)),
                ('workout_exercise_rest_time', models.CharField(max_length=50, null=True)),
                ('workout_exercise_time_between_set', models.CharField(max_length=50, null=True)),
                ('workout_exercise_created_by', models.CharField(max_length=50, null=True)),
                ('workout_exercise_updated_by', models.CharField(max_length=50, null=True)),
                ('workout_exercise_created_date', models.DateTimeField(null=True)),
                ('workout_exercise_status', models.CharField(default=b'Active', max_length=50, blank=True, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('exercise_id', models.ForeignKey(related_name='exercise_workout_id', to='trainmefitapp.Exercise', null=True)),
                ('workout_id', models.ForeignKey(related_name='workout_exe_id', to='trainmefitapp.Workout', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprogramworkoutmaster',
            name='workout_id',
            field=models.ForeignKey(related_name='user_programworkout_workout_id', to='trainmefitapp.Workout', null=True),
        ),
        migrations.AddField(
            model_name='userprogramexercisemap',
            name='user_program_workout_id',
            field=models.ForeignKey(related_name='user_program', to='trainmefitapp.UserProgramWorkoutMaster', null=True),
        ),
        migrations.AddField(
            model_name='programworkoutmap',
            name='workout_id',
            field=models.ForeignKey(related_name='program_workout_id', to='trainmefitapp.Workout', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_objective_id',
            field=models.ForeignKey(related_name='exercise_objective', to='trainmefitapp.ObjectiveMaster', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_video_id',
            field=models.ForeignKey(related_name='exercise_video', to='trainmefitapp.ExcerciseVideo', null=True),
        ),
    ]
